site_name: Hyperledger Fabric Node SDK
site_urlx: http://cdaughtr-fabric-sdk-node-docs.readthedocs.io
theme: readthedocs
repo_urlx: https://github.com/cdaughtr/fabric-sdk-node-docs.git
site_description: 'Welcome to the Hyperledger Fabric Node SDK documentation'
strict: true
theme_dir: 'docs/custom_theme'

pages:
- Home: index.md
- NodeSDK:
  - App-developer-env-setup: app-developer-env-setup.md
  - App-Overview: app-overview.md
  - Node-SDK-guide: node-sdk-guide.md
  - Node-SDK-indepth: node-sdk-indepth.md
  - Sample-Standalone-app: sample-standalone-app.md
  - Sample-web-app: sample-web-app.md

markdown_extensionsx:
  - toc:
     permalink: true
  - admonition
  - extra
  - tables
  - toc
  - fenced_code
  - smarty
  - footnotes

copyright: Copyright &copy; 2016 IBM Corp. <br></br>Contributed to the Hyperledger Project under the <a href="https://github.com/hyperledger/fabric/blob/master/LICENSE" target="_blank">Apache Software License 2.0</a>
